apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend1  # Label for identifying the pod's tier
spec:
  containers:
  - image: gamingapple0/week5:latest  # Docker image to use for the container
    name: nodewebapp  # Name of the container
    ports:
    - containerPort: 3000  # Port to expose on the container
  dnsPolicy: ClusterFirst  # DNS policy for the pod
  restartPolicy: Always  # Restart policy for the pod
